// The host country of a tournament from its location (pure, unit tested), as an IOC code to compare
// with players' nationalities. Locations come as "CITY, IOC", "CITY, COUNTRY[, STATE]" or a bare city.

const COUNTRY: Record<string, string> = {
  "UNITED STATES": "USA",
  USA: "USA",
  "GREAT BRITAIN": "GBR",
  CHINA: "CHN",
  "CHINESE TAIPEI": "TPE",
  AUSTRALIA: "AUS",
  MEXICO: "MEX",
  "UNITED ARAB EMIRATES": "UAE",
  ANDORRA: "AND",
  BELGIUM: "BEL",
  AZERBAIJAN: "AZE",
  SERBIA: "SRB",
  SWITZERLAND: "SUI",
  ROMANIA: "ROU",
  HUNGARY: "HUN",
  COLOMBIA: "COL",
  INDIA: "IND",
  ITALY: "ITA",
  BRAZIL: "BRA",
  CANADA: "CAN",
  GERMANY: "GER",
  THAILAND: "THA",
  TURKEY: "TUR",
  LATVIA: "LAT",
  POLAND: "POL",
  MALAYSIA: "MAS",
  SPAIN: "ESP",
  LUXEMBOURG: "LUX",
  FRANCE: "FRA",
  TUNISIA: "TUN",
  URUGUAY: "URU",
  RUSSIA: "RUS",
  KAZAKHSTAN: "KAZ",
  "CZECH REPUBLIC": "CZE",
  BOLIVIA: "BOL",
  ESTONIA: "EST",
  UZBEKISTAN: "UZB",
  ARGENTINA: "ARG",
  AUSTRIA: "AUT",
  SWEDEN: "SWE",
  JAPAN: "JPN",
  NETHERLANDS: "NED",
  PORTUGAL: "POR",
  GREECE: "GRE",
  CROATIA: "CRO",
  SLOVENIA: "SLO",
  SLOVAKIA: "SVK",
  BULGARIA: "BUL",
  "SOUTH KOREA": "KOR",
  KOREA: "KOR",
  CHILE: "CHI",
  ECUADOR: "ECU",
  PERU: "PER",
  "NEW ZEALAND": "NZL",
  QATAR: "QAT",
  "SAUDI ARABIA": "KSA",
  MOROCCO: "MAR",
  EGYPT: "EGY",
  ISRAEL: "ISR",
  GEORGIA: "GEO",
  FINLAND: "FIN",
  NORWAY: "NOR",
  DENMARK: "DEN",
  IRELAND: "IRL",
  PHILIPPINES: "PHI",
  SINGAPORE: "SGP",
  INDONESIA: "INA",
  VIETNAM: "VIE",
  "HONG KONG": "HKG",
  ANGOLA: "ANG",
};

// Bare city names (mostly ATP events).
const CITY: Record<string, string> = {
  "'S-HERTOGENBOSCH": "NED",
  ACAPULCO: "MEX",
  ADELAIDE: "AUS",
  ALMATY: "KAZ",
  AUCKLAND: "NZL",
  BARCELONA: "ESP",
  BASEL: "SUI",
  BASTAD: "SWE",
  BEIJING: "CHN",
  BOLOGNA: "ITA",
  BRISBANE: "AUS",
  BRUSSELS: "BEL",
  BUCHAREST: "ROU",
  "BUENOS AIRES": "ARG",
  CHENGDU: "CHN",
  CINCINNATI: "USA",
  DALLAS: "USA",
  "DELRAY BEACH": "USA",
  DOHA: "QAT",
  DUBAI: "UAE",
  EASTBOURNE: "GBR",
  ESTORIL: "POR",
  GENEVA: "SUI",
  GSTAAD: "SUI",
  HALLE: "GER",
  HAMBURG: "GER",
  HANGZHOU: "CHN",
  "HONG KONG": "HKG",
  HOUSTON: "USA",
  "INDIAN WELLS": "USA",
  KITZBUHEL: "AUT",
  LONDON: "GBR",
  "LOS CABOS": "MEX",
  LYON: "FRA",
  MADRID: "ESP",
  MALLORCA: "ESP",
  MARRAKECH: "MAR",
  MELBOURNE: "AUS",
  MIAMI: "USA",
  "MONTE-CARLO": "MON",
  MONTPELLIER: "FRA",
  MONTREAL: "CAN",
  MUNICH: "GER",
  "NEW YORK": "USA",
  PARIS: "FRA",
  "RIO DE JANEIRO": "BRA",
  ROME: "ITA",
  ROTTERDAM: "NED",
  SANTIAGO: "CHI",
  SHANGHAI: "CHN",
  STOCKHOLM: "SWE",
  STUTTGART: "GER",
  TOKYO: "JPN",
  TORONTO: "CAN",
  TURIN: "ITA",
  UMAG: "CRO",
  VIENNA: "AUT",
  WASHINGTON: "USA",
  "WINSTON-SALEM": "USA",
  WIMBLEDON: "GBR",
  ATLANTA: "USA",
  NEWPORT: "USA",
  ANTWERP: "BEL",
  METZ: "FRA",
  MARSEILLE: "FRA",
  SOFIA: "BUL",
  MOSCOW: "RUS",
  "ST. PETERSBURG": "RUS",
  "KUALA LUMPUR": "MAS",
  BANGALORE: "IND",
  PUNE: "IND",
  CHENNAI: "IND",
  QUITO: "ECU",
  "SAO PAULO": "BRA",
  CORDOBA: "ARG",
  BUDAPEST: "HUN",
  ISTANBUL: "TUR",
  GENOA: "ITA",
  PARMA: "ITA",
  CAGLIARI: "ITA",
  SARDINIA: "ITA",
  BELGRADE: "SRB",
  ZHUHAI: "CHN",
  SHENZHEN: "CHN",
  "LOS ANGELES": "USA",
  "LAS VEGAS": "USA",
  ORLANDO: "USA",
  "SAN DIEGO": "USA",
  ASTANA: "KAZ",
  "NUR-SULTAN": "KAZ",
  "TEL AVIV": "ISR",
  SYDNEY: "AUS",
  PERTH: "AUS",
  HOBART: "AUS",
  "GRAN CANARIA": "ESP",
  MARBELLA: "ESP",
  "CABO SAN LUCAS": "MEX",
  KAOHSIUNG: "TPE",
};

/** Host country (IOC) of a tournament location, or null when unknown or spread over several places. */
export function hostCountry(location: string | null): string | null {
  if (!location) return null;
  const parts = location.split(",").map((p) => p.trim().toUpperCase());
  for (const p of parts.slice(1)) {
    if (/^[A-Z]{3}$/.test(p) && p !== "USA") return p;
    if (COUNTRY[p]) return COUNTRY[p];
  }
  return CITY[parts[0]] ?? COUNTRY[parts[0]] ?? null;
}
